### ISSUE TITLE
Question: Are there any more code samples/tutorials?

### ISSUE THREAD

**Issue by twolfson** [tracyscott/RainbowStudio#2]
I've been trying to play around with the AudioOutput API but am having a hard time wrapping my head around the repo. Aside from my code, I see a bunch of code in this repo that I can't find documentation for anywhere (e.g. `GraphicMeter eq = lx.engine.audio.meter;` -- how did we know about `lx.engine.audio`, how did we know `meter` would be defined, etc)

I saw the recent Wiki addition to the README but I can't see anything covering that either =/

The Javadoc API has everything covered but no explanation behind usage/examples so I feel at a loss

http://lx.studio/api/

https://github.com/heronarts/LXStudio/wiki

**Comment by tracyscott** [comment]
Correct, there is very little documentation other than source code, the api reference, and examples.  I wrote up some notes on the UI in Notion.  I am super busy until Sunday but starting Monday I plan on writing documentation for a couple days.  For our Rainbow Equalizer, I looked at the code for https://github.com/heronarts/LX/blob/master/src/heronarts/lx/pattern/GraphicEqualizerPattern.java

For a lot of sample pattern implementations, check out Patterns.pde in the Tenere github.
https://github.com/treeoftenere/Tenere/tree/master/Tenere

One thing that might be slightly confusing with Tenere examples is that they are often operating on leaves.  We don't have that additional abstraction, so instead of setting the leaf color, we are just assigning the color directly for our points.  For example, notice the difference between our Tutorial pattern in Patterns.pde and their Tutorial pattern in Tenere/Tutorial.pde.

Just a couple of quick notes for implementing a pattern:

You can switch between the test panel and the full rainbow by changing this line in RainbowStudio.pde:

int modelType = FULL_RAINBOW; // RAINBOW_PANEL or FULL_RAINBOW

You may want to to delete your .lxproject file in ~/Documents/Processing/RainbowStudio/RainbowStudio (or wherever it is on your system) when switching between FULL_RAINBOW and RAINBOW_PANEL.  I force the camera position for the RAINBOW_PANEL case because the previous FULL_RAINBOW camera makes it hard to look at the panel.  The .lxproject file will keep track of your camera position so if you switch back and forth you might need to reposition the camera or delete your .lxproject file.  I should probably just force the camera position for both scenarios since I don't think preserving the previous camera position is that useful for our project.  You can pan the camera with command-click and drag on Mac.  Standard click and drag rotates the camera.

Our pixel/led coordinate system starts with 0,0 at the bottom left and width-1,height-1 at the top right.  This is opposite of typical image coordinate systems but is consistent with the world coordinate system.   Our coordinate system makes things like implementing an equalizer pattern easier.  The colors array is our pixel buffer.  So the array index of the second pixel (from the left) of the second row (from the bottom) would be index = row_index * width + column_index.  i.e.  1 * 420 + 1 = 421.  To set that pixel color: colors[index] = LXColor.rgb(127, 43, 255);  Just to make life exciting, our panels are wired differently.  They start at the bottom right of the panel and go up and then back down the next column to the left and then back up the next column to the left, etc.  You probably should not have to worry about that but if you do, the code is in SimplePanel.configureOutputRainbowPanel() in Model.pde.

The pixel color format is an int32 formatted as ARGB, one byte per channel.  For operating on colors, it is best to just use the methods in LXColor because those methods will handle the bit-shifting madness and clamping at 255 for you.  If you need to do something low-level with the bytes: promoting a byte to an int in Java while treating the byte as unsigned is extra annoying since Java doesn't have an 'unsigned byte'.  byte & 0xFF does the trick.  Typically, where you have my_byte = 0xFF; int a = my_byte; causes int a to be -1.  int a = my_byte & 0xFF; causes int a to be 255.  You can see an example in RenderImageUtil.getWeightedColor() that I use for antialiasing (still need to fix the alpha channel).

If you want to render to an image and then map it to the rainbow, check out the methods in RenderImageUtil.  I commented out the minimum bounding box version for now until I fix some bug in the antialiasing in that method.  Rendering to a texture that is the bounding box of the entire top half of the circle defined by our Rainbow's arc (RenderImageUtil.imageToPointsSemiCircle()) is preferable to the minimum bounding box because then your implementation can use the radius of the circle without an additional coordinate space transformation.  The negative is that it uses more memory and has larger areas of the texture that are not shown.  Either texture based approach suffers from aliasing because the LEDs in physical space are actually in polar coordinates (along an arc) so it is impossible for the LEDs to perfectly align with a rectangular (cartesian) image.  Some of our examples have an antialias knob so you can test the difference.  It is most noticeable with high frequency images like fast moving intersecting geometries.  It probably won't make much difference if your image is already something soft and low frequency like clouds.

If you are ok with the bend distortion or need it to be pixel perfect (e.g. pixel art), then just render to a 420x30 image and then use RenderImageUtil.imageToPointsPixelPerfect().  The limitation is that you will not be able to have a vertical line in physical space (except I guess at the very top of the rainbow).  This would matter if you wanted to implement something like rain.

For MIDI patterns, on Windows only one program at a time can open a MIDI port.  If you want to test your pattern and also generate sound you will need to install loopmidi https://www.tobias-erichsen.de/software/loopmidi.html  In loopmidi, create a virtual port called rainbowStudioOut. The BasicMidiPP pattern has an example of listening to MIDI notes and then passing them through to the rainbowStudioOut port.  I talked to Mark Slee (LX Studio author) about generic MIDI passthrough in the LX engine core but for the meantime, I will just implement a MidiPattern that all of our actual Midi patterns should extend.  The base class MidiPattern will handle the passthrough logic.  For your pattern to receive MIDI notes, you have to enable note monitoring for your controller (in the top right of your window in the OSC+MIDI component) and also on your channel strip in the bottom left of your window.  You should highlight the icon that looks like a musical note in both locations.  If you have knobs or sliders on your midi controller and want to control a knob parameter in your pattern, highlight the right facing arrow icon next to your midi controller.  Next, on the Midi Mappings component, highlight the same right facing arrow icon.  Now, your screen should be showing highlights on a bunch of elements in your interface.  Click on the knob in your pattern (for example 'bright' in the BasicMidiPP pattern).   Now turn a knob on your MIDI controller and under 'MIDI Mappings' you should see the mapping.  You need to press Escape or unhighlight the arrow next to 'MIDI Mappings' to exit mapping mode.  Now, when you turn the knob on your controller it should adjust the value of the knob for your pattern.

For OSC, I wrote a simple test in Android using Illposed JavaOSC.  It basically looks like this:
```
OSCPortOut oscPortOut = new OSCPortOut(InetAddress.getByName(myIP), myPort);
String[] thingsToSend = new String[1];
thingsToSend[0] = "/lx/channel/1/pattern/1/bright";
Object[] valuesToSend = new Float[1];
valuesToSend[0] = new Float(0.75);
OSCMessage message = new OSCMessage((String)thingsToSend[0], Arrays.asList(valuesToSend[0]));
oscPortOut.send(message);
```
The important part is "/lx/channel/1/pattern1/bright".  The BasicMidiPP pattern has a knob called 'bright' for controlling the background brightness.  This code will set that knob to .75 the max value, or 75% brightness.  The OSC address format is "/lx/channel/" + channel# (starts at 1 not zero) + "/pattern/" + pattern# (also starts at 1) + "/" + *knob*.  In the UI, when you hover over a knob, it will output the OSC address in the bottom status bar.

If you want to create your own control interface to play with your pattern and you don't have a MIDI controller, your best bet is TouchOSC.  There is a desktop application where you can layout sliders, knobs, buttons, etc and map them to OSC messages.  Once you have a layout, you can download it to your phone or preferably a tablet.  https://hexler.net/software/touchosc

**Comment by tracyscott** [comment]
One more note on MIDI.  For Tenere at Burning Man, they used an Akai APC40Mk2 for controlling the installation.  They implemented a class that maps the various Akai APC40Mk2 controls to various LX engine controls in this class:
https://github.com/heronarts/LX/blob/master/src/heronarts/lx/midi/surface/APC40Mk2.java

Having a hardware control interface is handy for experimental stuff like live playing the visuals (i.e. tuning the visuals to say whatever art car sound system shows up) because it has physical knobs you can twiddle but it would require both a wide toolset of patterns and somebody familiar enough with the patterns and parameters to synthesize something on the fly.  For just tuning patterns in general, something like touch osc would be fine and it operates over wifi.  Also, with the desire to have both the front and back of the rainbow operate independently, we would need 2 APC40Mk2's whereas we could change which side we are controlling with Touch OSC by changing the OSC port number.

**Comment by twolfson** [comment]
Wow, solid braindump. I don't have time to dig into all of this right now
but should do so by the end of the weekend

**Comment by twolfson** [comment]
Okay, read through everything with 28 minutes to spare. I don't have any further questions

I don't have any experience with things like OSC but it reminds me a lot of other buses like D-Bus. I appreciate the amount of detail and ground coverage

Thank for you all this =)
